FROM debian:bullseye-slim
COPY watchexec /usr/local/bin/watchexec
RUN chmod +x /usr/local/bin/watchexec && \
    ln -s /usr/local/bin/watchexec /watchexec
LABEL org.opencontainers.image.description="Watchexec x86_64 GNU/Linux"
ENTRYPOINT ["/usr/local/bin/watchexec"]
